title: Technology
email: pikachu77769@gmail.com
description: "pikachu987 Technology"

baseurl: ""
url: "/"

# baseurl:     "https://pikachu987.github.io/tec"
# url:         "/tec"

google_analytics: "UA-129769659-2"

github_username: pikachu987
notion_url: https://www.notion.so/Study-848fed3b628943bb945734c3ffe82d16
permalink: pretty # 주소 .html 확장자 제거
paginate: 10
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
