title: Technology
email: pikachu77769@gmail.com
description: "pikachu987 Technology"

baseurl:     ""

url:         "/tec"
# url:         "/"

google_analytics: "UA-129769659-2"

github_username: pikachu987
notion_url: https://www.notion.so/Study-848fed3b628943bb945734c3ffe82d16
permalink: pretty # 주소 .html 확장자 제거
paginate: 10
theme: minima
timezone: Europe/London
markdown: kramdown
encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-paginate

postarray:
  - title: Swift Firebase Facebook Login
    date: 2016-09-07 20:30:00
    summary: Firebase Facebook Login 페이스북 로그인
    link: https://pikachu987.github.io/tec/swift/2016/09/07/swiftFBLogin/
  - title: Swift Kakao Login
    date: 2016-09-11 08:30:00
    summary: 앞에서 했던 FacebookLogin에서 Kakao Login 카카오톡 로그인 추가하기
    link: https://pikachu987.github.io/tec/swift/2016/09/11/swiftKakaoLogin/
  - title: Swift Adobe Image Editor
    date: 2016-09-12 08:30:00
    summary: Adobe 이미지 에디터 사용해보기
    link: https://pikachu987.github.io/tec/swift/2016/09/12/swiftAdobeImageEditro/
  - title: cocoapods lib install
    date: 2017-01-10 10:00:00
    summary: ios cocoapods에서 라이브러리를 설치해보자!
    link: https://www.notion.so/pikachu987/Libaray-Install-567144882f14460aade08af59284740a
  - title: cocoapods lib create
    date: 2017-01-11 10:00:00
    summary: ios cocoapods에서 라이브러리를 생성해보자! (cocoapods lib create)
    path: 2017/01/11/cocoapodsCreate
    link: https://www.notion.so/pikachu987/Library-Create-fb00cc6dee8342579b6e795f60f4d22b
  - title: swift UIBezierPath Shape
    date: 2018-11-20 08:00:00
    summary: Swift UIBezierPath로 여러가지 도형, 말풍선 그리기(Arrow, Triangle, Square, Pentagon, Star, Heart, Bubble, Chat, Message)
    path: 2018/11/20/swift-bezier-path
    link: https://www.notion.so/pikachu987/UIBezierPath-Shape-80843bff46e5407c949d6b880518d670
  - title: swift PHAsset, Collections, Image progress
    date: 2018-11-22 08:00:00
    summary: Swift PHAsset을 사용해서 권한획득, Album List, Picture List, Get Image, iCloud Download Progress 확인하기
    path: 2018/11/22/swift-image-asset
    link: https://www.notion.so/pikachu987/PHAsset-ba2e4b2318cc4c339dc86c8aeea3c714
  - title: swift UILabel Text Gradation
    date: 2018-11-25 08:00:00
    summary: Swift UILabel의 텍스트에 Gradation 추가하기
    path: 2018/11/25/swift-label-text-gradation
    link: https://www.notion.so/pikachu987/Text-Gradation-60f6f084fab14475bcb466cf89d83078
  - title: swift Image Face Detector, Blur
    date: 2018-12-02 08:00:00
    summary: Swift 이미지에 얼굴찾고 얼굴 모자이크처리, 이미지로 씌우기
    path: swift-face-detector
    link: https://www.notion.so/pikachu987/Image-Face-Detector-4918efff89164e38998eefe5870f35ad
  - title: swift IBDesignable, IBInspectable
    date: 2018-12-03 08:00:00
    summary: Swift IBDesignable, IBInspectable 만들기
    path: 2018/12/02/swift-designable-inspectable
    link: https://www.notion.so/pikachu987/IBDesignable-IBInspectable-998cedbe8eb8401b9e189247b5b60e84
  - title: swift swizzling 스위즐링
    date: 2018-12-04 08:00:00
    summary: Swift swizzling 써보기
    path: 2018/12/04/swift-swizzling
    link: https://www.notion.so/pikachu987/Swizzling-60eb4c7af174426b88338608a072c353
  - title: swift subscript
    date: 2018-12-05 08:00:00
    summary: Swift subscript 써보기
    path: 2018/12/05/swift-subscript
    link: https://www.notion.so/pikachu987/Subscript-7ef5bdddf39e412685b5204c6fd4c249
  - title: swift 열거형 enumeration
    date: 2018-12-06 08:00:00
    summary: Swift enum 써보기 (associated value)
    path: 2018/12/06/swift-enum
    link: https://www.notion.so/pikachu987/Enumeration-2f28212ef645467c8027f1e0c7a00162
  - title: swift @escaping @noescape
    date: 2018-12-07 08:00:00
    summary: Swift @escaping @noescape 알아보기
    path: 2018/12/07/swift-escape
    link: https://www.notion.so/pikachu987/Escaping-noescaping-3df1c313224b4732842b9cdcd93c0ff5
  - title: swift ARC(Automatic Reference Counting)
    date: 2018-12-08 08:00:00
    summary: Swift ARC(Automatic Reference Counting) 자동계수참조 간단하게 알아보기
    path: 2018/12/08/swift-arc
    link: https://www.notion.so/pikachu987/ARC-Automatic-Reference-Counting-826c6bf8e2a046a884c3f9a63d99788a
  - title: swift LifeCycle
    date: 2018-12-09 08:00:00
    summary: Swift App LifeCycle과 ViewController의 LifeCycle
    path: 2018/12/09/swift-lifecycle
    link: https://www.notion.so/pikachu987/LifeCycle-0f28b79f7d4242c3888750445c981778
  - title: swift convenience 편의 생성자
    date: 2018-12-10 08:00:00
    summary: Swift convenience
    path: 2018/12/10/swift-convenience
    link: https://www.notion.so/pikachu987/Convenience-init-e281c16562a3421aa25b2895b9a507cf
  - title: swift associatedType 연관타입
    date: 2018-12-11 08:00:00
    summary: Swift protocol의 associatedType 써보기
    path: 2018/12/11/swift-associatedType
    link: https://www.notion.so/pikachu987/AssociatedType-10a59eeab738446b942d32e54c67e8e3
  - title: swift semaphore
    date: 2018-12-12 08:00:00
    summary: Swift semaphore 알아보기
    path: 2018/12/12/swift-semaphore
    link: https://www.notion.so/pikachu987/Semaphore-1ea293681b204350b8266def1456b313
  - title: swift blocking, non-blocking
    date: 2018-12-13 08:00:00
    summary: Swift sync, async, blocking, non-blocking에 대해 알아보자
    path: 2018/12/13/swift-blocking
    link: https://www.notion.so/pikachu987/Blocking-Non-blocking-887f501f067d4a06a0fab7b9495ec2bd
  - title: swift AutoLayout의 활용
    date: 2018-12-14 08:00:00
    summary: Swift AutoLayout의 Priority, Relation, 코드로 만들기, SnapKit
    path: 2018/12/14/swift-autolayout
    link: https://www.notion.so/pikachu987/AutoLayout-d32daa687fd04315b11647b9c8dfb773
  - title: swift Higher Order Functions (고차함수), 고차함수 만들기
    date: 2018-12-15 08:00:00
    summary: Swift Higher Order Functions 에 대해 알아보고 만들어보자
    path: 2018/12/15/swift-higerorderfunction
    link: https://www.notion.so/pikachu987/Higher-Order-Functions-444f549186b4475098ba656ba441b2fb
  - title: swift where의 사용
    date: 2018-12-16 08:00:00
    summary: Swift 여러군데에서 나오는 where을 사용해보자
    path: 2018/12/16/swift-where
    link: https://www.notion.so/pikachu987/where-Keyword-ce0a005b04004241b4b21a73feb0feb9
  - title: swift AccessControl 알아보기
    date: 2018-12-17 08:00:00
    summary: Swift open, public, internal, fileprivate, private
    path: 2018/12/17/swift-accesscontrol
    link: https://www.notion.so/pikachu987/AccessControl-dcac6d1243dd48a09815b2db748cc6e2
  - title: swift OptionSet 알아보기
    date: 2018-12-18 08:00:00
    summary: Swift OptionSet 만들어보고 enum과의 차이 알아보기
    path: 2018/12/18/swift-optionsset
    link: https://www.notion.so/pikachu987/OptionSet-245c80c696cc47e09011c617e63c899b
  - title: swift 표준 라이브러리 프로토콜에 대해 알아보기
    date: 2018-12-19 08:00:00
    summary: Swift equatable, comparable, sequence, iteratorProtocol, customStringConvertible
    path: 2018/12/19/swift-standardprotocol
    link: https://www.notion.so/pikachu987/Standard-Library-Protocol-c5e8fe314e1947c09bf0f5bd1e70ad04
  - title: swift final에 대해 알아보기
    date: 2018-12-20 08:00:00
    summary: Swift class final, method final, final class func과 class func과 static
    path: 2018/12/20/swift-finalstatic
    link: https://www.notion.so/pikachu987/final-Keyword-70067a09fcda424599323638000bf240
  - title: swift DispatchGroup 알아보기
    date: 2018-12-21 08:00:00
    summary: Swift DispatchGroup의 메서드에 대해 알아보기
    path: 2018/12/21/swift-dispatchgroup
    link: https://www.notion.so/pikachu987/DispatchGroup-bb7970004845440e8658540080cf8c5d
  - title: swift Declaration Attributes 알아보기
    date: 2018-12-22 08:00:00
    summary: Swift @objc, @escaping, @autoclosure, @discardableResult
    path: 2018/12/22/swift-declarationattributes
    link: https://www.notion.so/pikachu987/Declaration-Attributes-3970299595da4b85908d4354e25f625e
  - title: iOS UDID UUID ADID 알아보기
    date: 2019-01-21 08:00:00
    summary: iOS에서 사용하는 고유 ID 확인하기
    path: 2019/01/21/ios-id
    link: https://www.notion.so/pikachu987/UDID-UUID-ADID-463cd7fd72114d6b8ccd800809265dde
  - title: swift Throttle, Debounce
    date: 2019-01-29 08:00:00
    summary: 이벤트를 일정시간동안 후에 실행
    path: 2019/01/29/delay
    link: https://www.notion.so/pikachu987/Throttle-Debounce-005215de9cfc4574b49f43479c9fb46b
  - title: swift Generic
    date: 2019-10-26 08:00:00
    summary: Swift의 Generic에 대해 살펴보기
    link: https://www.notion.so/pikachu987/Generic-3cd14ee1d4454343a223926241b8461e
  - title: swift LRU LFU FIFO
    date: 2019-11-07 08:00:00
    summary: Swift로 만든 LRU LFU FIFO 페이지 교체 알고리즘
    link: https://www.notion.so/pikachu987/LRU-LFU-FIFO-44f8be48dc8449d6b9fba53937e7119d
  - title: swift Cache
    date: 2019-11-08 08:00:00
    summary: Swift의 MemoryCache, DiskCache
    link: https://www.notion.so/pikachu987/Cache-af5b4c0b99e443899cd8e13ccf6c3022
  - title: swift BackgroundFetch
    date: 2019-11-09 08:00:00
    summary: Swift의 Background상태에서도 동작하는 BackgroundFetch 이해하기
    link: https://www.notion.so/pikachu987/BackgroundFetch-4625f2b52cef47f19aa85ef5dd78a229
  - title: swift autoreleasepool
    date: 2019-11-10 08:00:00
    summary: Swift의 autoreleasepool에 대해 이해하기
    link: https://www.notion.so/pikachu987/autoreleasepool-6881ac755a4d456f83b3296cf2533dba
  - title: swift Array Optional Subscript(Indices, ~=)
    date: 2019-11-11 08:00:00
    summary: Swift의 Array에서 Optional로 Subscript사용하기
    link: https://www.notion.so/pikachu987/Array-Optional-Subscript-Indices-0803de67fd2344168dbb484f1df426e0
  - title: swift Struct initialization
    date: 2019-11-12 08:00:00
    summary: Swift의 Struct initialization 
    link: https://www.notion.so/pikachu987/Struct-initialization-0027d74f5ae94ef7a97ad91ce3163cfd
  - title: swift Class Struct == Operator
    date: 2019-11-13 08:00:00
    summary: Swift의 비교 연산자
    link: https://www.notion.so/pikachu987/Class-Struct-Operator-baaf2bfac5284461a842531fa0f7f94b
  - title: swift Class convenience init
    date: 2019-11-14 08:00:00
    summary: Swift의 Class convenience init 알아보기
    link: https://www.notion.so/pikachu987/Class-convenience-init-8ddc71314e2b41a78962e1dd76ae8ccf
  - title: swift Require
    date: 2019-11-15 08:00:00
    summary: Swift의 Require 알아보기
    link: https://www.notion.so/pikachu987/Require-97b54432955a426c8ac244abfde9156e
  - title: swift Mutating
    date: 2019-11-16 08:00:00
    summary: Swift의 Mutating 키워드 알아보기
    link: https://www.notion.so/pikachu987/Struct-Mutating-47445dd12fce4ce7bb7f383f4b555882
  - title: swift Reference Equal
    date: 2019-11-17 08:00:00
    summary: Swift의 Reference Equal 알아보기
    link: https://www.notion.so/pikachu987/Reference-Equal-52b059a3f3aa4470b7d6c2db56fdda12
  - title: swift KVC KVO
    date: 2019-11-18 08:00:00
    summary: Swift의 KVC KVO
    link: https://www.notion.so/pikachu987/KVC-KVO-dcc372b1ec2c4581b61ef4686de544ff
