title: Technology
email: pikachu77769@gmail.com
description: "pikachu987 Technology"

baseurl:     ""

url:         "/tec"
# url:         "/"

google_analytics: "UA-129769659-2"

github_username: pikachu987
tistory_url: https://pikachu987.tistory.com/
permalink: pretty # 주소 .html 확장자 제거
paginate: 10
theme: minima
timezone: Europe/London
markdown: kramdown
encoding: utf-8
plugins:
  - jekyll-feed
  - jekyll-paginate

postarray:
  - title: Swift Firebase Facebook Login
    date: 2016-09-07 20:30:00
    summary: Firebase Facebook Login 페이스북 로그인
    link: https://pikachu987.github.io/tec/swift/2016/09/07/swiftFBLogin/
  - title: Swift Kakao Login
    date: 2016-09-11 08:30:00
    summary: 앞에서 했던 FacebookLogin에서 Kakao Login 카카오톡 로그인 추가하기
    link: https://pikachu987.github.io/tec/swift/2016/09/11/swiftKakaoLogin/
  - title: Swift Adobe Image Editor
    date: 2016-09-12 08:30:00
    summary: Adobe 이미지 에디터 사용해보기
    link: https://pikachu987.github.io/tec/swift/2016/09/12/swiftAdobeImageEditro/
  - title: 티스토리로 이동합니다.
    date: 2019-11-24 08:00:00
    summary: 티스토리
    link: https://pikachu987.tistory.com/
